secret_key = { seed = 'test_seed' } # seed for generating keys
app_id = 0
log_level = 'info'
http_server_host = '0.0.0.0'
http_server_port = 7001
port = 37000
avail_path = '/home/avail/data'
bootstraps=['/dns/bootnode.2.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWRCgfvaLSnQfkwGehrhSNpY7i5RenWKL2ARst6ZqgdZZd','/dns/bootnode.1.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWBkLsNGaD3SpMaRWtAmWVuiZg1afdNSPbtJ8M8r9ArGRT']
full_node_ws=['wss://rpc-goldberg.sandbox.avail.tools:443','wss://avail-goldberg.public.blastapi.io:443','wss://lc-rpc-goldberg.avail.tools:443/ws','wss://avail2.polkadotters.com:443/ws','wss://avail-goldberg-rpc.polka.p2p.world:443']
confidence=80
kad_record_ttl=43200
ot_collector_endpoint='http://otelcol.lightclient.goldberg.avail.tools:4317'
genesis_hash='6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae'
block_processing_delay=100
